services:
  jekyll-text-theme_build:
    image: docker-jekyll-text-theme_dev
    environment:
      - JEKYLL_ENV=production
    volumes:
      - ..:/usr/src/app
    command: bundle exec jekyll build

  jekyll-text-theme_web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../_site:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jekyll-text-theme_build
    restart: unless-stopped