version: "3.5"

services:
  jekyll-text-theme_dev:
    image: docker-jekyll-text-theme_dev
    environment:
      - JEKYLL_ENV=development
    ports:
      - "1729:1729"
    container_name: jekyll-text-theme_dev
    volumes:
      - ..:/usr/src/app
    stdin_open: true
    tty: true
    command: >
      bundle exec jekyll serve
      -H 0.0.0.0
      -P 1729
      -t
      --force_polling
      --livereload